GET http://127.0.0.1:10001/movies/7
Accept: application/json

###

GET http://127.0.0.1:10001/movies/?director_id=12
Accept: application/json

###

GET http://127.0.0.1:10001/movies/?genre_id=4
Accept: application/json

###

GET http://127.0.0.1:10001/movies/?year=2010
Accept: application/json

###

GET http://127.0.0.1:10001/directors/
Accept: application/json

###

GET http://127.0.0.1:10001/directors/1
Accept: application/json

###

GET http://127.0.0.1:10001/genres/
Accept: application/json

###

GET http://127.0.0.1:10001/genres/1
Accept: application/json

###

GET http://127.0.0.1:10001/movies/
Accept: application/json

###

POST http://127.0.0.1:10001/movies/
Accept: application/json
Content-Type: application/json

{
  "title": "Пятачок --- кумир!",
  "trailer": "таким фильмам не нужны трейлеры",
  "year": 1993,
  "rating": 10,
  "description": "10 из 10!"
}

###

POST http://127.0.0.1:10001/users/
Accept: application/json
Content-Type: application/json

{
  "username": "test1",
  "password": "testp",
  "role": "testr"
}

###

POST http://127.0.0.1:10001/genres/
Accept: application/json
Content-Type: application/json

{
  "name": "test1"
}

###

PUT http://127.0.0.1:10001/movies/21
Accept: application/json
Content-Type: application/json

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 2022,
  "rating": 10,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

PATCH http://127.0.0.1:10001/movies/3
Accept: application/json
Content-Type: application/json

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

DELETE http://127.0.0.1:10001/users/5

###

POST http://127.0.0.1:10001/users/
Accept: application/json
Content-Type: application/json

{
  "username": "admin1",
  "password": "233445rt",
  "role": "admin"
}

###

POST http://127.0.0.1:10001/auth/
Accept: application/json
Content-Type: application/json

{
  "username": "admin1",
  "password": "233445rt"
}

###

PUT http://127.0.0.1:10001/auth/
Accept: application/json
Content-Type: application/json

{
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY2ODEwNTE0NH0.gtYebk71xSHMcZvGRW9G90gp34mHAL7-b8foBsV-86Q"
}